name: "Komodo Periphery"
description: "Used to remotly manage HA addons"
version: "1.0.0"
slug: "komodo_periphery"
init: false
arch:
  - aarch64
  - amd64
  - armv7
startup: services
ports:
  8120/tcp: 8120